//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""PlayerControls"",
            ""id"": ""02f9b0fb-b523-4a68-83f8-b4d9fc679772"",
            ""actions"": [
                {
                    ""name"": ""Vertical"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4021b428-cacb-4d65-8230-e82ec22bb14b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Horizontal"",
                    ""type"": ""Button"",
                    ""id"": ""3bcec326-42fb-4287-b0d1-ec654fe8b1d5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interaction"",
                    ""type"": ""Button"",
                    ""id"": ""d85436f9-ac5f-4d28-b1fd-778d10d4b912"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""84273204-c273-4476-9e6a-3bb9965c7814"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e84042c5-ec33-42d0-bbd7-47320b913fa4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ac5492b-0474-4fc8-8d35-b427eb57c842"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7cba084c-e9cf-4581-8df2-4c6fbd7a6540"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a64f3a13-52ff-46ec-9e87-529778e10a59"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interaction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""BattleUI"",
            ""id"": ""dd0e7386-6d17-4629-ac13-e0013f32c1ca"",
            ""actions"": [
                {
                    ""name"": ""NavigateUp"",
                    ""type"": ""Button"",
                    ""id"": ""0229c10e-9376-4859-9429-142a08fb0daa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateDown"",
                    ""type"": ""Button"",
                    ""id"": ""3fd25822-a0f5-4a42-8713-bd23be9799c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""e65b549c-9af7-4913-aa1f-987c490c9834"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateLeft"",
                    ""type"": ""Button"",
                    ""id"": ""88becf78-a75f-4056-a52a-53a74d0d7e66"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NavigateRight"",
                    ""type"": ""Button"",
                    ""id"": ""114ce7b3-5a53-4440-abf4-368330174060"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""3e48987d-b972-420b-b925-4aeb41fd95be"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""dfe4709f-bbab-4d02-99cc-7e80644d288b"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""227ed1a9-383b-4cdf-b894-0218bb36bbc1"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2a83a09f-64ca-4d73-946e-0333531121d2"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""baa42085-f56f-4af3-91db-58da05e55949"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9221fdc3-013d-494c-a734-df0f64b6c2ec"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""13210ad6-d600-485a-ad10-b5f6703bbabf"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba148722-5856-415e-8415-bfe5b2206669"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd03ca61-2c5c-48a4-8e62-50ccac6df9c8"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa73eafe-32ca-442b-b8f5-742a272a5489"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c4a7372-88a0-413a-804c-9f9d799f04e1"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NavigateRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""679add91-c24f-4e11-b766-f5e02270293e"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""OverWorldUI"",
            ""id"": ""417b591b-dafb-4b77-9fc6-04a4ac9a9c64"",
            ""actions"": [
                {
                    ""name"": ""Continue"",
                    ""type"": ""Button"",
                    ""id"": ""553f41da-4b63-4962-8949-6f8c19336dc7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PartyBack"",
                    ""type"": ""Button"",
                    ""id"": ""ebdef413-4f4c-47c0-a6d5-9cae1e9cfb91"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveRight"",
                    ""type"": ""Button"",
                    ""id"": ""50cab82e-f638-4b37-bab9-d0f1b1aed5f8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveLeft"",
                    ""type"": ""Button"",
                    ""id"": ""13aade85-a5ed-4d9d-8014-74dedcac011c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PartyConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""92a36b0a-f405-4896-803f-42e6a58aa4d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveDown"",
                    ""type"": ""Button"",
                    ""id"": ""70d59a47-6119-4af0-940d-27970dc71b12"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveUp"",
                    ""type"": ""Button"",
                    ""id"": ""96a301b8-c459-4c76-af62-f36e32e2b4fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""12b745fd-b3be-4707-ab62-45d5cdb276c4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Continue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6960cbb-4d21-4ed2-b876-6fab02caf858"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ebf6ffd6-52a6-456f-a1c0-18cce3ac52a3"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a2e6e44-3e2e-41c6-93d8-b86cf2143b1f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""36ebff25-2c75-4364-a685-768d3658816e"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2fea827-9e8b-487b-a890-fc551dbc3514"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PartyConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0976d67-68d9-4fae-9073-85bdc5898e20"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PartyConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22a7ef72-63a7-4736-ad5b-9b2dc58b3aa5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""304d31ce-a27d-4c65-af63-2adb84e109bc"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""542f0051-3041-4182-baeb-9929bf917664"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91f20ed5-fc34-41bc-b71d-49a15be0da4d"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76ac2290-39b7-47c4-9c32-99d81c2f2a6c"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PartyBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControls
        m_PlayerControls = asset.FindActionMap("PlayerControls", throwIfNotFound: true);
        m_PlayerControls_Vertical = m_PlayerControls.FindAction("Vertical", throwIfNotFound: true);
        m_PlayerControls_Horizontal = m_PlayerControls.FindAction("Horizontal", throwIfNotFound: true);
        m_PlayerControls_Interaction = m_PlayerControls.FindAction("Interaction", throwIfNotFound: true);
        // BattleUI
        m_BattleUI = asset.FindActionMap("BattleUI", throwIfNotFound: true);
        m_BattleUI_NavigateUp = m_BattleUI.FindAction("NavigateUp", throwIfNotFound: true);
        m_BattleUI_NavigateDown = m_BattleUI.FindAction("NavigateDown", throwIfNotFound: true);
        m_BattleUI_Confirm = m_BattleUI.FindAction("Confirm", throwIfNotFound: true);
        m_BattleUI_NavigateLeft = m_BattleUI.FindAction("NavigateLeft", throwIfNotFound: true);
        m_BattleUI_NavigateRight = m_BattleUI.FindAction("NavigateRight", throwIfNotFound: true);
        m_BattleUI_Back = m_BattleUI.FindAction("Back", throwIfNotFound: true);
        // OverWorldUI
        m_OverWorldUI = asset.FindActionMap("OverWorldUI", throwIfNotFound: true);
        m_OverWorldUI_Continue = m_OverWorldUI.FindAction("Continue", throwIfNotFound: true);
        m_OverWorldUI_PartyBack = m_OverWorldUI.FindAction("PartyBack", throwIfNotFound: true);
        m_OverWorldUI_MoveRight = m_OverWorldUI.FindAction("MoveRight", throwIfNotFound: true);
        m_OverWorldUI_MoveLeft = m_OverWorldUI.FindAction("MoveLeft", throwIfNotFound: true);
        m_OverWorldUI_PartyConfirm = m_OverWorldUI.FindAction("PartyConfirm", throwIfNotFound: true);
        m_OverWorldUI_MoveDown = m_OverWorldUI.FindAction("MoveDown", throwIfNotFound: true);
        m_OverWorldUI_MoveUp = m_OverWorldUI.FindAction("MoveUp", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControls
    private readonly InputActionMap m_PlayerControls;
    private IPlayerControlsActions m_PlayerControlsActionsCallbackInterface;
    private readonly InputAction m_PlayerControls_Vertical;
    private readonly InputAction m_PlayerControls_Horizontal;
    private readonly InputAction m_PlayerControls_Interaction;
    public struct PlayerControlsActions
    {
        private @PlayerInput m_Wrapper;
        public PlayerControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Vertical => m_Wrapper.m_PlayerControls_Vertical;
        public InputAction @Horizontal => m_Wrapper.m_PlayerControls_Horizontal;
        public InputAction @Interaction => m_Wrapper.m_PlayerControls_Interaction;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlsActions instance)
        {
            if (m_Wrapper.m_PlayerControlsActionsCallbackInterface != null)
            {
                @Vertical.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnVertical;
                @Vertical.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnVertical;
                @Vertical.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnVertical;
                @Horizontal.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnHorizontal;
                @Horizontal.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnHorizontal;
                @Horizontal.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnHorizontal;
                @Interaction.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteraction;
                @Interaction.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteraction;
                @Interaction.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnInteraction;
            }
            m_Wrapper.m_PlayerControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Vertical.started += instance.OnVertical;
                @Vertical.performed += instance.OnVertical;
                @Vertical.canceled += instance.OnVertical;
                @Horizontal.started += instance.OnHorizontal;
                @Horizontal.performed += instance.OnHorizontal;
                @Horizontal.canceled += instance.OnHorizontal;
                @Interaction.started += instance.OnInteraction;
                @Interaction.performed += instance.OnInteraction;
                @Interaction.canceled += instance.OnInteraction;
            }
        }
    }
    public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);

    // BattleUI
    private readonly InputActionMap m_BattleUI;
    private IBattleUIActions m_BattleUIActionsCallbackInterface;
    private readonly InputAction m_BattleUI_NavigateUp;
    private readonly InputAction m_BattleUI_NavigateDown;
    private readonly InputAction m_BattleUI_Confirm;
    private readonly InputAction m_BattleUI_NavigateLeft;
    private readonly InputAction m_BattleUI_NavigateRight;
    private readonly InputAction m_BattleUI_Back;
    public struct BattleUIActions
    {
        private @PlayerInput m_Wrapper;
        public BattleUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @NavigateUp => m_Wrapper.m_BattleUI_NavigateUp;
        public InputAction @NavigateDown => m_Wrapper.m_BattleUI_NavigateDown;
        public InputAction @Confirm => m_Wrapper.m_BattleUI_Confirm;
        public InputAction @NavigateLeft => m_Wrapper.m_BattleUI_NavigateLeft;
        public InputAction @NavigateRight => m_Wrapper.m_BattleUI_NavigateRight;
        public InputAction @Back => m_Wrapper.m_BattleUI_Back;
        public InputActionMap Get() { return m_Wrapper.m_BattleUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BattleUIActions set) { return set.Get(); }
        public void SetCallbacks(IBattleUIActions instance)
        {
            if (m_Wrapper.m_BattleUIActionsCallbackInterface != null)
            {
                @NavigateUp.started -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateUp;
                @NavigateUp.performed -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateUp;
                @NavigateUp.canceled -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateUp;
                @NavigateDown.started -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateDown;
                @NavigateDown.performed -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateDown;
                @NavigateDown.canceled -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateDown;
                @Confirm.started -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnConfirm;
                @Confirm.performed -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnConfirm;
                @Confirm.canceled -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnConfirm;
                @NavigateLeft.started -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateLeft;
                @NavigateLeft.performed -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateLeft;
                @NavigateLeft.canceled -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateLeft;
                @NavigateRight.started -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateRight;
                @NavigateRight.performed -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateRight;
                @NavigateRight.canceled -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnNavigateRight;
                @Back.started -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_BattleUIActionsCallbackInterface.OnBack;
            }
            m_Wrapper.m_BattleUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @NavigateUp.started += instance.OnNavigateUp;
                @NavigateUp.performed += instance.OnNavigateUp;
                @NavigateUp.canceled += instance.OnNavigateUp;
                @NavigateDown.started += instance.OnNavigateDown;
                @NavigateDown.performed += instance.OnNavigateDown;
                @NavigateDown.canceled += instance.OnNavigateDown;
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
                @NavigateLeft.started += instance.OnNavigateLeft;
                @NavigateLeft.performed += instance.OnNavigateLeft;
                @NavigateLeft.canceled += instance.OnNavigateLeft;
                @NavigateRight.started += instance.OnNavigateRight;
                @NavigateRight.performed += instance.OnNavigateRight;
                @NavigateRight.canceled += instance.OnNavigateRight;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
            }
        }
    }
    public BattleUIActions @BattleUI => new BattleUIActions(this);

    // OverWorldUI
    private readonly InputActionMap m_OverWorldUI;
    private IOverWorldUIActions m_OverWorldUIActionsCallbackInterface;
    private readonly InputAction m_OverWorldUI_Continue;
    private readonly InputAction m_OverWorldUI_PartyBack;
    private readonly InputAction m_OverWorldUI_MoveRight;
    private readonly InputAction m_OverWorldUI_MoveLeft;
    private readonly InputAction m_OverWorldUI_PartyConfirm;
    private readonly InputAction m_OverWorldUI_MoveDown;
    private readonly InputAction m_OverWorldUI_MoveUp;
    public struct OverWorldUIActions
    {
        private @PlayerInput m_Wrapper;
        public OverWorldUIActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Continue => m_Wrapper.m_OverWorldUI_Continue;
        public InputAction @PartyBack => m_Wrapper.m_OverWorldUI_PartyBack;
        public InputAction @MoveRight => m_Wrapper.m_OverWorldUI_MoveRight;
        public InputAction @MoveLeft => m_Wrapper.m_OverWorldUI_MoveLeft;
        public InputAction @PartyConfirm => m_Wrapper.m_OverWorldUI_PartyConfirm;
        public InputAction @MoveDown => m_Wrapper.m_OverWorldUI_MoveDown;
        public InputAction @MoveUp => m_Wrapper.m_OverWorldUI_MoveUp;
        public InputActionMap Get() { return m_Wrapper.m_OverWorldUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(OverWorldUIActions set) { return set.Get(); }
        public void SetCallbacks(IOverWorldUIActions instance)
        {
            if (m_Wrapper.m_OverWorldUIActionsCallbackInterface != null)
            {
                @Continue.started -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnContinue;
                @Continue.performed -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnContinue;
                @Continue.canceled -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnContinue;
                @PartyBack.started -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnPartyBack;
                @PartyBack.performed -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnPartyBack;
                @PartyBack.canceled -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnPartyBack;
                @MoveRight.started -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveRight;
                @MoveRight.performed -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveRight;
                @MoveRight.canceled -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveRight;
                @MoveLeft.started -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.performed -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveLeft;
                @MoveLeft.canceled -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveLeft;
                @PartyConfirm.started -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnPartyConfirm;
                @PartyConfirm.performed -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnPartyConfirm;
                @PartyConfirm.canceled -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnPartyConfirm;
                @MoveDown.started -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveDown;
                @MoveDown.performed -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveDown;
                @MoveDown.canceled -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveDown;
                @MoveUp.started -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveUp;
                @MoveUp.performed -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveUp;
                @MoveUp.canceled -= m_Wrapper.m_OverWorldUIActionsCallbackInterface.OnMoveUp;
            }
            m_Wrapper.m_OverWorldUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Continue.started += instance.OnContinue;
                @Continue.performed += instance.OnContinue;
                @Continue.canceled += instance.OnContinue;
                @PartyBack.started += instance.OnPartyBack;
                @PartyBack.performed += instance.OnPartyBack;
                @PartyBack.canceled += instance.OnPartyBack;
                @MoveRight.started += instance.OnMoveRight;
                @MoveRight.performed += instance.OnMoveRight;
                @MoveRight.canceled += instance.OnMoveRight;
                @MoveLeft.started += instance.OnMoveLeft;
                @MoveLeft.performed += instance.OnMoveLeft;
                @MoveLeft.canceled += instance.OnMoveLeft;
                @PartyConfirm.started += instance.OnPartyConfirm;
                @PartyConfirm.performed += instance.OnPartyConfirm;
                @PartyConfirm.canceled += instance.OnPartyConfirm;
                @MoveDown.started += instance.OnMoveDown;
                @MoveDown.performed += instance.OnMoveDown;
                @MoveDown.canceled += instance.OnMoveDown;
                @MoveUp.started += instance.OnMoveUp;
                @MoveUp.performed += instance.OnMoveUp;
                @MoveUp.canceled += instance.OnMoveUp;
            }
        }
    }
    public OverWorldUIActions @OverWorldUI => new OverWorldUIActions(this);
    public interface IPlayerControlsActions
    {
        void OnVertical(InputAction.CallbackContext context);
        void OnHorizontal(InputAction.CallbackContext context);
        void OnInteraction(InputAction.CallbackContext context);
    }
    public interface IBattleUIActions
    {
        void OnNavigateUp(InputAction.CallbackContext context);
        void OnNavigateDown(InputAction.CallbackContext context);
        void OnConfirm(InputAction.CallbackContext context);
        void OnNavigateLeft(InputAction.CallbackContext context);
        void OnNavigateRight(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
    }
    public interface IOverWorldUIActions
    {
        void OnContinue(InputAction.CallbackContext context);
        void OnPartyBack(InputAction.CallbackContext context);
        void OnMoveRight(InputAction.CallbackContext context);
        void OnMoveLeft(InputAction.CallbackContext context);
        void OnPartyConfirm(InputAction.CallbackContext context);
        void OnMoveDown(InputAction.CallbackContext context);
        void OnMoveUp(InputAction.CallbackContext context);
    }
}
